# ekf_config.yaml

topics:
  input_topic: "sensor"
  output_topic: "orientation"

ekf:
  dt_min: 0.001
  
  initial_covariance:
    orientation_scale: 0.00001
    # CRÍTICO: Bias inicial ZERO. Começamos confiando que é 0.
    bias_scale: 0.000000001  

  # Ruído de Processo (Q)
  # Os 3 últimos valores são a "Variação do Bias do Giroscópio".
  # Colocamos 1e-9 (quase zero) para travar o aprendizado do bias.
  # O filtro vai assumir que o erro do giroscópio NUNCA muda.
  process_noise: [0.001, 0.001, 0.001, 0.000000001, 0.000000001, 0.000000001]

  measurement_noise:
    # Acelerômetro alto para evitar que andar para frente incline o cubo
    accel_factor: 0.2  
    # Magnetômetro baixo (confiança alta) pois o simulador não tem interferência magnética
    mag_factor: 10

magnetometer:
  # Bias zero pois o simulador gera dados centralizados
  bias: [0.0, 0.0, 0.0]
  scale: [1.0, 1.0, 1.0]

dead_reckoning:
  gravity_vector: [0.0, 0.0, 1.0]
  calibration_frames: 10
  
  thresholds:
    general: 0.05
    z_axis: 0.08
    
  stationary_tolerance: 0.03 
  
  drag:
    xy: 0.90       
    z: 0.85        
    
  floor_constraint: true
  return_to_center: false